# Generated by Django 5.2.7 on 2026-01-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('seller', 'فروشنده'), ('buyer', 'خریدار')], default='buyer', max_length=10, verbose_name='نقش کاربر'),
        ),
    ]
