# Generated by Django 5.2.7 on 2025-11-07 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد تخفیف')),
                ('discount_percent', models.IntegerField(verbose_name='درصد تخفیف')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان فایل')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('category', models.CharField(choices=[('book', 'کتاب'), ('music', 'موسیقی'), ('article', 'مقاله'), ('image', 'تصویر'), ('other', 'سایر')], max_length=20, verbose_name='دسته\u200cبندی')),
                ('file', models.FileField(upload_to='uploads/', verbose_name='فایل')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت (تومان)')),
                ('keywords', models.CharField(blank=True, max_length=200, verbose_name='کلمات کلیدی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='فروشنده')),
            ],
            options={
                'verbose_name': 'فایل دیجیتال',
                'verbose_name_plural': 'فایل\u200cهای دیجیتال',
                'ordering': ['-created_at'],
            },
        ),
    ]
