# Generated by Django 5.2.7 on 2026-01-28 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(help_text='فایل اصلی قابل دانلود (مثلاً pdf, zip, mp3).', upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'zip', 'rar', '7z', 'mp3', 'wav', 'png', 'jpg', 'jpeg'])], verbose_name='فایل محصول'),
        ),
    ]
