# Generated by Django 5.2.7 on 2025-12-12 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_seller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'محصولات', 'verbose_name_plural': 'محصولات'},
        ),
    ]
